name: Zap MFA

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: |
          echo "export ZAP_USERNAME=$ZAP_USERNAME" >> $GITHUB_ENV
          echo "export ZAP_PASSWORD=$ZAP_PASSWORD" >> $GITHUB_ENV
   

      - name: Run Zap Scan
        run: |
           docker run --rm -v $(pwd):/zap/wrk/:z -t ictu/zap2docker-weekly zap-baseline.py -I -j \
            -t https://saint-gobain-uk--perftestin.sandbox.my.salesforce.com/  --hook=.zap/auth_hook.py \
            -z "auth.loginurl=https://saint-gobain-uk--perftestin.sandbox.my.salesforce.com/_ui/identity/verification/method/TotpVerificationUi/e \
                auth.username=gomathy.gopinath@qualitestgroup.com.perftesin \
                auth.password=Qualisecure$123 \
                auth.username_field=un \
                auth.password_field=pw \
                auth.submit_field=Login" * OUTOFSCOPE .*\.js
                                       
              
